config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  
  root 'welcome#index'
  
  resources :users do
    resource :profile do
      member do
        put :published_toggle
      end
    end
    collection do
      post :import
    end
  end
  
  resources :groups
end

app/models/ability.rb
class Ability
  include CanCan::Ability

  def initialize(user)
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/group.rb
class Group < ActiveRecord::Base
  has_and_belongs_to_many :users
  has_many :profiles, :through => :users
  has_many :articles, :through => :users
  belongs_to :parent, :foreign_key => "parent_id", :class_name => "Group"
  validates :name, :presence => true
end

app/models/user.rb
class User < ApplicationRecord
  devise :database_authenticatable, :registerable, :rememberable, :trackable
  
  validates :login, :presence => true, 
            :length => { :maximum => 50 }, 
            :uniqueness => true
  validates :password, :confirmation => true,
            :length => { :minimum => 8 },
            :presence => true
  validates :password_confirmation, :presence => true
  
  has_and_belongs_to_many :groups
  has_one :profile
  
  def admin?
    self.groups.where(administrator: true).count > 0
  end
  
  def moderator?
    self.groups.where(moderator: true).count > 0
  end
  
  def writer?
    self.groups.where(writer: true).count > 0
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  rescue_from CanCan::AccessDenied do |exception|
    respond_to do |format|
      format.json { head :forbidden, content_type: 'text/html' }
      format.html { redirect_to main_app.root_url, notice: exception.message }
      format.js   { head :forbidden, content_type: 'text/html' }
    end
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  load_and_authorize_resource
  before_action :set_group, only: [:show, :edit, :update, :destroy]
  before_action :set_groups, only: [:index, :new, :edit]

  # GET /groups
  # GET /groups.json
  def index
  end

  # GET /groups/1
  # GET /groups/1.json
  def show
  end

  # GET /groups/new
  def new
    @group = Group.new
  end

  # GET /groups/1/edit
  def edit
  end

  # POST /groups
  # POST /groups.json
  def create
    @group = Group.new(group_params)

    respond_to do |format|
      if @group.save
        format.html { redirect_to @group, notice: 'Group was successfully created.' }
        format.json { render action: 'show', status: :created, location: @group }
      else
        format.html { render action: 'new' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /groups/1
  # PATCH/PUT /groups/1.json
  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to @group, notice: 'Group was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /groups/1
  # DELETE /groups/1.json
  def destroy
    @group.destroy
    respond_to do |format|
      format.html { redirect_to groups_url }
      format.json { head :no_content }
    end
  end
  
  def add_to
    Group.find(params[:id]).users << User.find(params[:user_id])
    redirect_to :back
  end
  
  def remove_from
    Group.find(params[:id]).users.delete(User.find(params[:user_id]))
    redirect_to :back
  end
  
  def current_ability
    @current_ability ||= GroupAbility.new(current_user)
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_group
      @group = Group.includes(:profiles).find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def group_params
      params.require(:group).permit(:name, :administrator, :moderator, :writer, :reader, :commentator, :parent_id)
    end
    
    def set_groups
      @groups = Group.all
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  load_and_authorize_resource
  before_action :set_user, only: [:show]
  before_action :user_params
  
  def index
    @users = User.select(:id, :login).includes(:groups, :profile).order('profiles.updated_at DESC').where(profiles: user_params).paginate(page: params[:page])
    @all_users = User.select(:id, :login).order(:login).includes('profile')
    respond_to do |format|
      format.html
#       format.xls
    end
  end

  def show
    redirect_to user_profile_path(@user)
  end

  def import
    User.import(params[:file])
    redirect_to users_url, notice: "Users imported."
  end
  
  def current_ability
    @current_ability ||= UserAbility.new(current_user)
  end
  
  private
  def set_user
    @user = User.find(params[:id])
  end
  
  def user_params
    params.permit(:published)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/groups/_form.html.slim
= form_for @group, html: { class: 'form-horizontal' } do |f|
  .grid-x.grid-padding-x.align-center
    .medium-6.cell
      .input-group
        span.input-group-label= f.label :name
        = f.text_field :name, class: 'input-group-field'
      .input-group
        span.input-group-label= f.label 'parent_id'
        = f.select :parent_id, options_for_select = @groups.collect {|p| [t(p.name, scope: [:groups]), p.id] }, {include_blank: ''}, class: 'input-group-field'
      fieldset
        = f.check_box :administrator
        = f.label :administrator
        = f.check_box :moderator
        = f.label :moderator
        = f.check_box :writer
        = f.label :writer
        = f.check_box :reader
        = f.label :reader
      .form-actions
        = f.submit nil, class: 'button tiny'
        = link_to t('.cancel', :default => t("helpers.links.cancel")), groups_path, class: 'button tiny'

app/views/groups/edit.html.slim
.page-header
  h1 Редактировать группу
= render partial: 'form'

app/views/groups/index.html.slim
.page-header
  h1 Группы
table
  thead
    tr
      th Название
      th Администратор
      th Модератор
      th Писатель
      th Читатель
      th Действия
  tbody
    - @groups.each do |group|
      tr
        td= link_to t(group.name, scope: :groups), group_path(group)
        td= group.administrator? ? "+" : "-"
        td= group.moderator? ? "+" : "-"
        td= group.writer ? "+" : "-"
        td= group.reader? ? "+" : "-"
        td
          = link_to 'Редактировать', edit_group_path(group), class: 'btn btn-mini'
          span &nbsp|&nbsp
          = link_to 'Удалить', group_path(group), method: :delete, data: {confirm: 'Уверены?'}, class: 'btn btn-mini btn-danger'
= link_to 'Добавить группу', new_group_path, class: 'button tiny'

app/views/groups/new.html.slim
.page-header
  h1 Новая группа
= render partial: 'form'

app/views/groups/show.html.slim
section.panel
  h1= t(@group.name, scope: :groups)
  ul.no-bullet
    li= "администратор: #{@group.administrator? ? "+" : "-"}"
    li= "модератор: #{@group.moderator? ? "+" : "-"}"
    li= "писатель: #{@group.writer? ? "+" : "-"}"
    li= "читатель: #{@group.reader? ? "+" : "-"}"
    li= "комментатор: #{@group.commentator? ? "+" : "-"}"
  ul
    - @group.users.sort_by(&:created_at).each do |user|
      li= user.profile.full_name.empty? ? (link_to user.login, edit_user_profile_path(user)) : (link_to user.profile.full_name, user_profile_path(user))

app/views/layouts/application.html.slim
doctype html
html lang="en"
  head
    meta charset="utf-8"
    meta name="viewport" content="width=device-width, initial-scale=1.0"

    title == content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = csrf_meta_tag

  body
    p.notice= notice
    == yield

app/views/users/index.html.erb
<section class="panel">
<div class='right'>
  <% if @administrator_permission %>
    <h2>Импорт пользователей</h2>
    <%= form_tag import_users_path, multipart: true do %>
      <%= file_field_tag :file %>
      <%= submit_tag "Загрузить" %>
    <% end %>
  <%= link_to 'Скачать список пользователей', users_path(format: :xls) %>
  <% end %>
</div>
<h1>Список пользователей</h1>
<%= will_paginate @users, next_label: "Вперед", previous_label: 'Назад' %>
<hr />
<dl>
  <% @users.each do |user| %>
    <dt>
      <% if @administrator_permission %>
        <span>&nbsp;</span>
        <%= link_to published_toggle_user_profile_path(user), title: 'Опубликовать', class: 'right', method: :put do %>
          <i class="fi-eye"></i>
        <% end %>
      <% end %>
    <%= user.login %>
| дата регистрации: <%= user.created_at.to_date %>
    </dt>
    <dd>
    <%= user.profile.full_name.empty? ? (link_to 'Профиль не заполнен', edit_user_profile_path(user)) : (link_to user.profile.full_name, user_profile_path(user)) %>
      <ul class='inline-list'>
	<% user.groups.each do |g| %>
	  <li><%= link_to t(g.name, scope: :groups), g %></li>
	<% end %>
      </ul>
    </dd>
  <% end %>
<dl>
</seciton>

app/views/users/index.xls.erb
<?xml version="1.0"?>
<Workbook xmlns="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:o="urn:schemas-microsoft-com:office:office"
  xmlns:x="urn:schemas-microsoft-com:office:excel"
  xmlns:ss="urn:schemas-microsoft-com:office:spreadsheet"
  xmlns:html="http://www.w3.org/TR/REC-html40">
  <Worksheet ss:Name="Sheet1">
    <Table>
      <Row>
        <Cell><Data ss:Type="String">id</Data></Cell>
        <Cell><Data ss:Type="String">login</Data></Cell>
	<Cell><Data ss:Type="String">password</Data></Cell>
	<Cell><Data ss:Type="String">password_confirmation</Data></Cell>
        <Cell><Data ss:Type="String">last_name</Data></Cell>
        <Cell><Data ss:Type="String">first_name</Data></Cell>
	<Cell><Data ss:Type="String">middle_name</Data></Cell>
	<Cell><Data ss:Type="String">academic_title</Data></Cell>
	<Cell><Data ss:Type="String">degree</Data></Cell>
	<Cell><Data ss:Type="String">email</Data></Cell>
	<Cell><Data ss:Type="String">phone</Data></Cell>
      </Row>
    <% @all_users.each do |user| %>
      <Row>
        <Cell><Data ss:Type="Number"><%= user.id %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.login %></Data></Cell>
	<Cell><Data ss:Type="String"></Data></Cell>
	<Cell><Data ss:Type="String"></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.profile.last_name if user.profile.last_name %></Data></Cell>
        <Cell><Data ss:Type="String"><%= user.profile.first_name if user.profile.first_name %></Data></Cell>
	<Cell><Data ss:Type="String"><%= user.profile.middle_name if user.profile.middle_name %></Data></Cell>
	<Cell><Data ss:Type="String"><%= user.profile.academic_title.name if user.profile.academic_title %></Data></Cell>
	<Cell><Data ss:Type="String"><%= user.profile.degree.name if user.profile.degree %></Data></Cell>
	<Cell><Data ss:Type="String"><%= user.profile.email if user.profile.email %></Data></Cell>
	<Cell><Data ss:Type="String"><%= user.profile.phone if user.profile.phone %></Data></Cell>
      </Row>
      <% end %>
    </Table>
  </Worksheet>
</Workbook>

app/views/users/show.html.erb
<h1>Users#show</h1>
<p>Find me in app/views/users/show.html.erb</p>

app/views/welcome/index.html.slim
= link_to 'Выйти', destroy_user_session_path, method: "delete", class: 'button'
= link_to 'Войти', new_user_session_path, class: 'button'